blog/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogapp.urls')),
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogapp/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views




urlpatterns = [
    path('', views.BlogHomeView.as_view(), name='blog-home'),
    path('detail/<int:pk>/', views.BlogDetailView.as_view(), name='detail-view'),
    path('register/', views.registerPage, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='blogapp/login.html'), name='login'),
    path('logout/', views.logoutPage, name='logout'),
    path('profile/', views.profilePage, name='profile'),
    path('create/', views.BlogCreateView.as_view(), name='blog-create'),
    path('update/<int:pk>/', views.BlogUpdateView.as_view(), name='blog-update'),
    path('delete/<int:pk>/', views.BlogDeleteView.as_view(), name='blog-delete'),
    path('userbloglist/<int:pk>/', views.UserBlogListView.as_view(), name='user-blog-list'),
    path('mybloglist/', views.MyBlogListView.as_view(), name='my-blog-list'),
    path('testpage/<int:pk>/', views.testpage, name='testpage'),
    path('ajaxx/', views.ajaxcomments, name='testcommentpage'),


      # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), 
        name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'), 
        name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
     name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),

    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),

    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
     name='password_reset_complete'),

]

blogapp/models.py
from django.urls import reverse
from django.db import models
from django.db.models.signals import pre_save, post_delete
from django.utils.text import slugify
from django.conf import settings
from django.dispatch import receiver
from random import random

def upload_location(instance, filename):
	file_path = f"blogapp/{instance.author.id}/{instance.title}-{filename}"
	return file_path

class BlogPost(models.Model):

	title 				= models.CharField(max_length=100, null=False, blank=False)
	content				= models.TextField(max_length=5000, null=False, blank=False)
	date_posted			= models.DateTimeField(auto_now_add=True, verbose_name='date posted')
	date_updated		= models.DateTimeField(auto_now=True, verbose_name='date updated')
	image				= models.ImageField(upload_to=upload_location, default='default-prof-pic.jpg' ,null=True, blank=True)
	author				= models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	slug 				= models.SlugField(blank=True, unique=True)

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('detail-view', kwargs={'pk':self.pk})


@receiver(pre_save, sender=BlogPost)
def confirm_sluf_field(sender, instance, *args, **kwargs):
	if not instance.slug:
		randstr = str(random()*1000000)
		instance.slug = slugify(instance.author.username + '-' + instance.title + '-' + randstr)
		

@receiver(post_delete, sender=BlogPost)
def upon_deletion(sender, instance, **kwargs):
	instance.image.delete(False)

class Comment(models.Model):

	post 				= models.ForeignKey(BlogPost, on_delete=models.CASCADE)
	author				= models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	comment 			= models.TextField(max_length=500, null=False, blank=False)
	date_posted 		= models.DateTimeField(auto_now_add=True, verbose_name='date posted')

	def __str__(self):
		return self.author.username



	
	

blogapp/forms.py
from django import forms
from .models import Comment


class CommentCreationForm(forms.ModelForm):
	class Meta:
		model = Comment
		fields = ['comment']

blogapp/views.py
from django.shortcuts import render, redirect
from django.views.generic import (
	DetailView,
	ListView,
	CreateView,
	UpdateView,
	DeleteView,
	FormView
	)
from django.contrib.auth import authenticate, login, logout 
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.db.models import Q
from account.models import Account
from .forms import CommentCreationForm
from account.forms import UserRegistrationForm, AccountUpdationForm
from django.contrib import messages
from .models import BlogPost, Comment
from django.http import JsonResponse
import json
from datetime import datetime





# Create your views here.
@login_required(login_url='login')
def homepage(request, *args, **kwargs):
	accounts = Account.objects.all()
	context = {
		'accounts': accounts,
	}
	query = ""
	if request.GET:
		query = request.GET['q']





	return render(request, 'blogapp/home.html', context)

def registerPage(request, *args, **kwargs):
	form = UserRegistrationForm(request.POST or None)
	if form.is_valid():
		user = form.save()
		messages.success(request, 'Account was created for ' + user.username)
		return redirect('login')

	context = {
		'form': form,
		'url' : 'login',
	}

	return render(request, 'blogapp/register.html', context)

def loginPage(request, *args, **kwargs):

	if request.method == "POST":
		email 		= request.POST.get("email")
		password 	= request.POST.get("password")
		user 		= authenticate(email=email, password=password)
		if user:
			login(request, user)
			return redirect('/')
		else:
			messages.info(request, "Email OR Password is not correct")
	context = {
		'url' : 'login',
	}
	return render(request, 'blogapp/login.html', context)

@login_required(login_url='login')
def logoutPage(request, *args, **kwargs):
	logout(request)
	return redirect("login")

@login_required(login_url='login')
def profilePage(request, *args, **kwargs):
	user = request.user
	pic = user.profile_pic.url
	form = AccountUpdationForm(request.POST or None, request.FILES or None, instance=user)

	if form.is_valid():
		form.save()
		return redirect('/')
	context = {
		'form': form,
		'pic': pic,
	}
	return render(request, 'blogapp/profile.html', context)

class BlogHomeView(ListView):
	model 			= BlogPost
	template_name 	= "blogapp/home.html"  #<appName>/<view>_<model>//
	# ordering = ['-date_posted']
	paginate_by 	= 10

	def get_queryset(self):
		query = self.request.GET.get('q', None)
		if query is not None:
			object_list = self.model.objects.filter(
				Q(title__icontains=query) |
				Q(content__icontains=query) |
				Q(author__username__icontains=query)
				).order_by('-date_posted')
		else:
			object_list = self.model.objects.all().order_by('-date_posted')
		return object_list




class BlogDetailView(DetailView):
	model = BlogPost

	

class BlogCreateView(LoginRequiredMixin, CreateView):
	model = BlogPost
	fields = ['title', 'content', 'image']

	def form_valid(self, form):
		form.instance.author = self.request.user
		return super().form_valid(form)

class BlogUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
	model = BlogPost
	fields = ['title', 'content', 'image']

	def form_valid(self, form):
		form.instance.author = self.request.user
		return super().form_valid(form)

	def test_func(self):
		post = self.get_object()
		if self.request.user == post.author:
			return True
		return False

class BlogDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
	model = BlogPost
	success_url = '/'

	def test_func(self):
			post = self.get_object()
			if self.request.user == post.author:
				return True
			return False


class UserBlogListView(DetailView):
	
	model 				= Account
	template_name 		= "blogapp/user_profiles.html"
	paginate_by 		= 10


class MyBlogListView(LoginRequiredMixin, ListView):

	model 				= BlogPost
	template_name 		= "blogapp/my_blog_list.html"
	paginate_by 		= 10

	def get_queryset(self):

		user 			= self.request.user
		object_list 	= self.model.objects.filter(author=user).order_by('-date_posted')
		return object_list



def testpage(request, pk):

	verbal = Comment.objects.all().order_by('-date_posted')
	author = Account.objects.get(username=request.user)
	post = BlogPost.objects.get(pk=pk)

	if request.method == "POST":
		content = request.POST.get('content')
		print(request.POST)
		new_comment = Comment.objects.create(comment=content, author=author, post=post)
		responseObj = {
		'author': new_comment.author.username,
		'content':new_comment.comment,
		'date_posted':str(new_comment.date_posted),
		
		
		}
		new_comment.save()
		print('url is ', new_comment.author.profile_pic.url)
		return JsonResponse(json.dumps(responseObj), safe=False)

	
	context = {
	'post':post,
	'comments':verbal,
	}

	return render(request, 'blogapp/testpage.html', context)



def ajaxcomments(request):
	verbal = Comment.objects.all()
	author = Account.objects.get(pk=1)
	post = BlogPost.objects.get(pk=10)

	if request.method == "POST":
		content = request.POST.get('content')
		print(request.POST)
		new_comment = Comment.objects.create(comment=content, author=author, post=post)
		x = datetime(new_comment.date_posted).strftime("%d %B %Y")


		responseObj = {
		'author': new_comment.author.username,
		'content':new_comment.comment,
		'date_posted':str(x),
		'url':new_comment.author.profile_pic.url,
		
		}
		new_comment.save()
		print('url is', responseObj)
		return JsonResponse(json.dumps(responseObj), safe=False)

	context = {
	'comments':verbal,
	}

	return render(request, 'blogapp/ajaxcomments.html', context)

templates/blogapp/ajaxcomments.html
{% extends 'blogapp/base.html' %}

{% block title %}
<title>{{post.title}}</title>
{% endblock %}

{% block body %}

	<div class="container">
		<h3 class="font-weight-bold my-4">Comments</h3>
		<hr>
		<form action="" method="POST" id="myForm"> {% csrf_token %}

			<textarea name="content" id="contents" class="form-control mb-s2 col-md-8" rows="5"></textarea>
			<input type="submit" value="Add Comment" id="inputBtn" class="btn btn-primary mt-3 mb-4">
		</form>
	</div>
	<div class="container" id="container">
		<div id="newComment">

		</div>
		{% for comment in comments|dictsortreversed:"date_posted" %}
		<div class="card col-md-8 mt-2 mb-3 bg-white pt-3 px-4 shadow-sm">
			<p>
				<a href="#" class="h3 text-info">
					{{comment.author}}
				</a> 
				<small>{{comment.date_posted}}
				</small>
			</p>
			<p class="h4">
				{{comment.comment}}
				
				<p class="h6 mt-2 mb-0 text-right"><a href="#" class="btn btn-sm btn-outline-primary mr-2"><svg width="1em" height="1em" style="position: relative;top: -3px" viewBox="0 0 16 16" class="bi bi-hand-thumbs-up" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
					<path fill-rule="evenodd" d="M6.956 1.745C7.021.81 7.908.087 8.864.325l.261.066c.463.116.874.456 1.012.965.22.816.533 2.511.062 4.51a9.84 9.84 0 0 1 .443-.051c.713-.065 1.669-.072 2.516.21.518.173.994.681 1.2 1.273.184.532.16 1.162-.234 1.733.058.119.103.242.138.363.077.27.113.567.113.856 0 .289-.036.586-.113.856-.039.135-.09.273-.16.404.169.387.107.819-.003 1.148a3.163 3.163 0 0 1-.488.901c.054.152.076.312.076.465 0 .305-.089.625-.253.912C13.1 15.522 12.437 16 11.5 16v-1c.563 0 .901-.272 1.066-.56a.865.865 0 0 0 .121-.416c0-.12-.035-.165-.04-.17l-.354-.354.353-.354c.202-.201.407-.511.505-.804.104-.312.043-.441-.005-.488l-.353-.354.353-.354c.043-.042.105-.14.154-.315.048-.167.075-.37.075-.581 0-.211-.027-.414-.075-.581-.05-.174-.111-.273-.154-.315L12.793 9l.353-.354c.353-.352.373-.713.267-1.02-.122-.35-.396-.593-.571-.652-.653-.217-1.447-.224-2.11-.164a8.907 8.907 0 0 0-1.094.171l-.014.003-.003.001a.5.5 0 0 1-.595-.643 8.34 8.34 0 0 0 .145-4.726c-.03-.111-.128-.215-.288-.255l-.262-.065c-.306-.077-.642.156-.667.518-.075 1.082-.239 2.15-.482 2.85-.174.502-.603 1.268-1.238 1.977-.637.712-1.519 1.41-2.614 1.708-.394.108-.62.396-.62.65v4.002c0 .26.22.515.553.55 1.293.137 1.936.53 2.491.868l.04.025c.27.164.495.296.776.393.277.095.63.163 1.14.163h3.5v1H8c-.605 0-1.07-.081-1.466-.218a4.82 4.82 0 0 1-.97-.484l-.048-.03c-.504-.307-.999-.609-2.068-.722C2.682 14.464 2 13.846 2 13V9c0-.85.685-1.432 1.357-1.615.849-.232 1.574-.787 2.132-1.41.56-.627.914-1.28 1.039-1.639.199-.575.356-1.539.428-2.59z"/>
				</svg> Like</a> 
				<a href="#" class="btn btn-sm btn-outline-primary"><svg width="1em" height="1em" style="position: relative;top: -3px" viewBox="0 0 16 16" class="bi bi-chat-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
					<path d="M8 15c4.418 0 8-3.134 8-7s-3.582-7-8-7-8 3.134-8 7c0 1.76.743 3.37 1.97 4.6-.097 1.016-.417 2.13-.771 2.966-.079.186.074.394.273.362 2.256-.37 3.597-.938 4.18-1.234A9.06 9.06 0 0 0 8 15z"/>
				</svg> Reply</a></p>
			</p>
		</div>

		{% endfor %}


	</div>

{% endblock %}

{% block script %}
<script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
<script>
	console.log("Javascript online")
	myForm = document.getElementById("myForm");
	myForm.addEventListener("submit", (e) => {
		e.preventDefault();
		contents = document.getElementById("contents").value;
		console.log(contents)

		$.ajax({
			url: {% url 'testcommentpage' %},
			type: "POST",
			data: $("#myForm").serialize(),
			success: function (data) {
				let comment = JSON.parse(data);
				document.getElementById("newComment").innerHTML += `
				<h3 class="font-weight-bold">
				${comment.author}
				</h3>
				<p>${comment.content}</p>
				<small>${comment.date_posted}</small>
				`;

				document.getElementById("contents").value = "";
				console.log(data)

				;
			}
		})
	});



</script>




{% endblock %}

templates/blogapp/blogpost_confirm_delete.html
{% extends 'blogapp/base.html' %}

{% block title %}
<title>Welcome to MyBlog</title>
{% endblock %}

{% block body %}

<div class="container mt-4 mb-2 col-md-6">

	{% load crispy_forms_tags %}

	<form action="" method="POST"> {% csrf_token %}
	<p class="h3 font-weight-bolder my-2">Are you sure you want to delete <span class="text-info">"{{object.title}}"</span> post?</p>	
	<div class="text-center my-3">
	<input type="submit" value="Delete" class="btn btn-danger">
	<a class="btn btn-secondary" href="{% url 'detail-view' object.id %}">Cancel</a>
	</div>
	</form>
</div>

{% endblock %}

templates/blogapp/blogpost_detail.html
{% extends 'blogapp/base.html' %}

{% block title %}
<title>{{object.title}}</title>
{% endblock %}

{% block body %}

<div class="container my-4">
{{object.blogpost_set.all}}
	<div class="jumbotron bg-white">
		<h1 class="display-4 font-amaranth mb-3">{{object.title}}</h1>
		<p class="text-center">
			<img src="{{object.image.url}}" width="100%" height="600px" alt="">
		</p>
		<hr class="my-4">

		<p> <span style="font-size: 3rem;" class="font-amaranth">{{object.content|slice:1}}</span>{{object.content|slice:"1:"}}</p>

		<p class="text-muted text-right mb-0 mx-4" style="font-size: 1.3rem;">- <a href="{% url 'user-blog-list' object.author.id %}"> {{object.author.first_name}} {{object.author.last_name}} </a></p>

	</div>
	{% if user == object.author %}
	<div>
		<a href="{% url 'blog-update' object.id %}" class="btn btn-secondary">Edit Blog</a>
		<a href="{% url 'blog-delete' object.id %}" class="btn btn-danger">Delete Blog</a>
	</div>
	{% endif %}

</div>


{% endblock %}

templates/blogapp/blogpost_form.html
{% extends 'blogapp/base.html' %}

{% block title %}

	{% if request.path_info == "/create/" %}
<title>Create Blog</title>
	{% else %}
<title>Edit Blog</title>
	{% endif %}

{% endblock %}



{% block body %}

<div class="container mt-4 mb-2 col-md-4">

	{% load crispy_forms_tags %}

	{% if request.path_info == "/create/" %}
		<h2 class="text-center">Create Post</h2>
	{% else %}
		<h2 class="text-center">Edit Post</h2>
	{% endif %}

	<form action="" method="POST" enctype="multipart/form-data"> {% csrf_token %}
		{{form|crispy}}
		<input type="submit" value="Post" class="btn btn-block btn-outline-primary">
	</form>
</div>
{% endblock %}

templates/blogapp/home.html
{% extends 'blogapp/base.html' %}

{% block title %}
<title>Welcome to MyBlog</title>
{% endblock %}

{% block body %}

<div class="container">

	<div class="d-lg-none col-lg-8 my-4">
		<a class="btn btn-block btn-light" href="{% url 'blog-create' %}">
			<svg width="1.5em" height="1.5em" viewBox="0 0 16 16" class="bi bi-file-earmark-plus text-primary font-weight-bold mx-2" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
				<path d="M9 1H4a2 2 0 0 0-2 2v10a2 2 0 0 0 2 2h5v-1H4a1 1 0 0 1-1-1V3a1 1 0 0 1 1-1h5v2.5A1.5 1.5 0 0 0 10.5 6H13v2h1V6L9 1z"/>
				<path fill-rule="evenodd" d="M13.5 10a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1H13v-1.5a.5.5 0 0 1 .5-.5z"/>
				<path fill-rule="evenodd" d="M13 12.5a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 0 1H14v1.5a.5.5 0 0 1-1 0v-2z"/>
			</svg>
			Create Post
			
		</a>
	</div>	


	<div class="row">
		<div class="d-flex flex-column col-lg-8">
			{% if object_list %}

			{% for object in object_list %}
			<div class="card my-2">
				<div class="card-header">
					<img src="{{object.author.profile_pic.url}}" alt="" class="img-thumbnail rounded-circle img-fluid" width="45px" height="45px">
					
				 <a class="text-primary" href="{% url 'user-blog-list' object.author.id %}">{{object.author}}</a>
				</div>

				<div class="card-body">
					<h4 class="card-title">
						<a href="{% url 'testpage' object.id %}"> <span class="font-weight-bold text-dark font-weight-bold"> {{object.title}} </span></a>
					</h4>
					<img src="{{object.image.url}}" class="card-img-top mb-2" alt="...">
					<p class="card-text">
						{{object.content|truncatechars:500}} 
						<a href="{% url 'detail-view' object.id %}">
							Read more
						</a>
					</p>
				</div>

				<div class="card-footer text-muted text-right bg-light">
					Posted on {{object.date_posted|date:"d F o"}} @ {{object.date_posted|time:"f A"}}
				</div>

			</div>
			{% endfor %}

			{% else %}
			<h1 class="text-center my-2">No blogs have been posted yet.</h1>
			{% endif %}

		</div>

		<div class="d-lg-inline d-none flex-column col-lg-4 my-2">

			<div>
				{% if user.is_authenticated %}
				<h4 class="text-dark text-center font-weight-bold mt-4 mb-2">
					Welcome, {{request.user.first_name}} {{request.user.last_name}}
				</h4>
				<!-- <img src="{{user.profile_pic.url}}" class="img-fluid rounded-circle my-3" alt=""> -->
				
				{% endif %}
				<p class="border border-secondary p-3 bg-white">
					Share your ideas, knowledge and content with others in order to break the geographical barriers.
				</p>
			</div>


			<a class="btn btn-block btn-light pl-0" href="{% url 'blog-create' %}">
				<svg width="1.5em" height="1.5em" viewBox="0 0 16 16" class="bi bi-file-earmark-plus text-primary font-weight-bold mx-2" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
					<path d="M9 1H4a2 2 0 0 0-2 2v10a2 2 0 0 0 2 2h5v-1H4a1 1 0 0 1-1-1V3a1 1 0 0 1 1-1h5v2.5A1.5 1.5 0 0 0 10.5 6H13v2h1V6L9 1z"/>
					<path fill-rule="evenodd" d="M13.5 10a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1H13v-1.5a.5.5 0 0 1 .5-.5z"/>
					<path fill-rule="evenodd" d="M13 12.5a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 0 1H14v1.5a.5.5 0 0 1-1 0v-2z"/>
				</svg>
				Create Post
			</a>

		</div>
	</div>

					<!-- PAGINATION -->

	{% if is_paginated %}

		{% if page_obj.has_previous %}
	
			<a href="?page=1" class="btn btn-outline-info mb-4">First</a>
			<a href="?page={{page_obj.previous_page_number}}" class="btn btn-outline-info mb-4">Previous</a>
		
		{% endif %}

		{% for num in page_obj.paginator.page_range %}

			{% if page_obj.number == num %}

			<a href="?page={{num}}" class="btn btn-info mb-4">{{num}}</a>

			{% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
				
				<a href="?page={{num}}" class="btn btn-outline-info mb-4">{{num}}</a>
				

			{% endif %}

		{% endfor %}
		

		{% if page_obj.has_next %}
	
			<a href="?page={{page_obj.next_page_number}}" class="btn btn-outline-info mb-4">Next</a>
			<a href="?page={{page_obj.paginator.num_pages}}" class="btn btn-outline-info mb-4">Last</a>
		
		{% endif %}

	{% endif %}
</div>
	{% endblock %}

templates/blogapp/user_profiles.html
{% extends 'blogapp/base.html' %}

{% block title %}
<title>Welcome to MyBlog</title>
{% endblock %}

{% block body %}

<div class="container">

	<div class="row">
		<div class="d-flex flex-column col-lg-8">
			{% if object.blogpost_set.all.count > 0 %}

			{% for object in object.blogpost_set.all|dictsortreversed:"date_posted" %}
			<div class="card my-2">
				<div class="card-header">
					<img src="{{object.author.profile_pic.url}}" alt="" class="img-thumbnail rounded-circle img-fluid" width="60px" height="60px">
					
					<a class="text-primary" href="{% url 'user-blog-list' object.author.id%}">{{object.author}}</a>
				</div>

				<div class="card-body">
					<h4 class="card-title">
						<a href="{% url 'detail-view' object.id %}"> <span class="font-weight-bold text-dark font-weight-bold"> {{object.title}} </span></a>
					</h4>
					<img src="{{object.image.url}}" class="card-img-top mb-2" alt="...">
					<p class="card-text">
						{{object.content|truncatechars:500}} 
						<a href="{% url 'detail-view' object.id %}">
							Read more
						</a>
					</p>
				</div>

				<div class="card-footer text-muted text-right bg-light">
					Posted on {{object.date_posted|date:"d F o"}} @ {{object.date_posted|time:"f A"}}
				</div>

			</div>
			{% endfor %}

			{% else %}
			<h1 class="text-center my-2">No blogs have been posted yet.</h1>
			{% endif %}

		</div>

		<div class="d-lg-inline d-none flex-column col-lg-4 my-2">

			<div>
				{% if user.is_authenticated %}
				
				<h4 class="text-dark text-center font-weight-bold mt-4 mb-2">
					{{object.first_name}} {{object.last_name}}
				</h4>
				<img src="{{object.profile_pic.url}}" class="img-fluid rounded-circle my-3" alt="">
				
				{% endif %}
				
			</div>


			

		</div>
	</div>

	<!-- PAGINATION -->

	{% if is_paginated %}

	{% if page_obj.has_previous %}
	
	<a href="?page=1" class="btn btn-outline-info mb-4">First</a>
	<a href="?page={{page_obj.previous_page_number}}" class="btn btn-outline-info mb-4">Previous</a>

	{% endif %}

	{% for num in page_obj.paginator.page_range %}

	{% if page_obj.number == num %}

	<a href="?page={{num}}" class="btn btn-info mb-4">{{num}}</a>

	{% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}

	<a href="?page={{num}}" class="btn btn-outline-info mb-4">{{num}}</a>


	{% endif %}

	{% endfor %}


	{% if page_obj.has_next %}
	
	<a href="?page={{page_obj.next_page_number}}" class="btn btn-outline-info mb-4">Next</a>
	<a href="?page={{page_obj.paginator.num_pages}}" class="btn btn-outline-info mb-4">Last</a>

	{% endif %}

	{% endif %}
</div>












{% endblock %}